---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present
  become: true

- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  become: true

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: grafana
  become: true

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: false
  become: true

- name: Enable and start grafana-server
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
  become: true

- name: Configure Prometheus Datasource
  ansible.builtin.copy:
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    content: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://localhost:9090
          isDefault: true
    owner: root
    group: grafana
    mode: '0644'
  become: true
  notify: Restart Grafana

- name: Create dashboards directory
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'
  become: true

- name: Configure Dashboard Provider
  ansible.builtin.copy:
    dest: /etc/grafana/provisioning/dashboards/default.yml
    content: |
      apiVersion: 1
      providers:
        - name: 'Default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          options:
            path: /var/lib/grafana/dashboards
    owner: root
    group: grafana
    mode: '0644'
  become: true
  notify: Restart Grafana

- name: Copy Spark Cluster Dashboard
  ansible.builtin.copy:
    src: spark-cluster-overview.json
    dest: /var/lib/grafana/dashboards/spark-cluster-overview.json
    owner: grafana
    group: grafana
    mode: '0644'
  become: true
