#!/bin/bash

# Summary:
# This script updates the Ansible inventory file from the Terraform outputs.
# It retrieves the IP addresses of the master, edge, and worker nodes from Terraform and updates the inventory file.
# The inventory file is then used by Ansible to manage the cluster.

set -e

echo "Updating Ansible inventory from Terraform outputs..."

# Go to terraform directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../terraform"
INVENTORY_FILE="$SCRIPT_DIR/inventory/hosts.yml"

cd "$TERRAFORM_DIR"

# Check if terraform state exists
if [ ! -f "terraform.tfstate" ]; then
    echo "Error: Terraform state not found. Please deploy infrastructure first."
    echo "Run: cd terraform && terraform apply"
    exit 1
fi

# Get IPs from Terraform
echo "Retrieving IPs from Terraform..."

MASTER_IP=$(terraform output -raw master_external_ip 2>/dev/null || echo "")
EDGE_IP=$(terraform output -raw edge_external_ip 2>/dev/null || echo "")
WORKER_IPS=$(terraform output -json worker_external_ips 2>/dev/null || echo "[]")

# Parse worker IPs
NUM_WORKERS=$(echo "$WORKER_IPS" | jq '. | length')

# Check if we got the IPs
if [ -z "$MASTER_IP" ] || [ "$MASTER_IP" == "null" ]; then
    echo "Error: Could not retrieve IPs from Terraform."
    echo "Is the infrastructure deployed?"
    exit 1
fi

echo "Retrieved IPs:"
echo "  Master:   $MASTER_IP"
for (( i=0; i<$NUM_WORKERS; i++ )); do
    IP=$(echo "$WORKER_IPS" | jq -r ".[$i]")
    echo "  Worker $((i+1)): $IP"
done
echo "  Edge:     $EDGE_IP"

# Generate inventory 
echo ""
echo "Generating inventory file..."

cat > "$INVENTORY_FILE" << EOF
# Inventory file for GCP
# This file is automatically generated by the update_inventory.sh script when the infrastructure is deployed
# Do not modify this file manually
---
all:
  children:
    spark_cluster:
      children:
        master:
          hosts:
            spark-master:
              ansible_host: $MASTER_IP

        workers:
          hosts:
EOF

# Add workers dynamically
for (( i=0; i<$NUM_WORKERS; i++ )); do
    IP=$(echo "$WORKER_IPS" | jq -r ".[$i]")
    cat >> "$INVENTORY_FILE" << EOF
            spark-worker-$((i+1)):
              ansible_host: $IP
EOF
done

# Add edge and vars
cat >> "$INVENTORY_FILE" << EOF

        edge:
          hosts:
            spark-edge:
              ansible_host: $EDGE_IP

  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/gcp_spark
    ansible_python_interpreter: /usr/bin/python3
EOF

echo ""
echo "[SUCCESS] Inventory updated successfully!"
echo "File: $INVENTORY_FILE"
echo ""
echo "Test connectivity with:"
echo "  ansible all -i ansible/inventory/hosts.yml -m ping"